[rmkit] Fix missing header related to OKP single-header
After commit 2fd7055 most apps would not build for the kobo target.
Example build output below :

```
$ TARGET=kobo DOCKERFILE=Dockerfile.kobo FBINK=1 make harmony_docker

CXX=arm-kobo-linux-gnueabihf-g++ okp -sh -ig "RMKIT_IMPLEMENTATION" -ns -ni -for -d ../.rmkit.h_cpp/ -o ../build/rmkit.h rmkit.cpy ../build/stb.arm.o -- -D"KOBO=1" -D"RMKIT_IMPLEMENTATION" -ldl -pthread -lpthread -fdata-sections -ffunction-sections -Wl,--gc-sections -L/rmkit/src/vendor/FBInk/Release -l:libfbink.a -D"RMKIT_FBINK=1" -O2 -static -static-libstdc++ -static-libgcc
compile flags: -DKOBO=1 -DRMKIT_IMPLEMENTATION -ldl -pthread -lpthread -fdata-sections -ffunction-sections -Wl,--gc-sections -L/rmkit/src/vendor/FBInk/Release -l:libfbink.a -DRMKIT_FBINK=1 -O2 -static -static-libstdc++ -static-libgcc
missing file: ../shared/proc.h
missing file: ../shared/string.h
generating single header /rmkit/src/rmkit/../build/rmkit.h
MISSING FILE! /rmkit/src/.rmkit.h_cpp/shared/proc.h
MISSING FILE! /rmkit/src/.rmkit.h_cpp/shared/string.h
compiled into /rmkit/src/.rmkit.h_cpp
missing file: ../shared/proc.h
missing file: ../shared/proc.h
missing file: ../shared/proc.h
missing file: ../shared/proc.h
missing file: ../shared/proc.h
missing file: ../shared/proc.h
missing file: ../shared/proc.h
missing file: ../shared/string.h
make[2]: Leaving directory '/rmkit/src/rmkit'
make[1]: Leaving directory '/rmkit/src/rmkit'
cd src/harmony && make
make[1]: Entering directory '/rmkit/src/harmony'
make compile_kobo
make[2]: Entering directory '/rmkit/src/harmony'
make[3]: Entering directory '/rmkit/src/vendor/FBInk'
make[3]: Nothing to be done for 'staticlib'.
make[3]: Leaving directory '/rmkit/src/vendor/FBInk'
CXX=arm-kobo-linux-gnueabihf-g++ okp -ig "RMKIT_IMPLEMENTATION" -ns -ni -for -d ../.harmony_cpp/ -o ../build/harmony main.cpy ../build/stb.arm.o -- -D"KOBO=1" -D"RMKIT_IMPLEMENTATION" -ldl -pthread -lpthread -fdata-sections -ffunction-sections -Wl,--gc-sections -L/rmkit/src/vendor/FBInk/Release -l:libfbink.a -D"RMKIT_FBINK=1" -Wno-psabi -O2 -static -static-libstdc++ -static-libgcc
compile flags: -DKOBO=1 -DRMKIT_IMPLEMENTATION -ldl -pthread -lpthread -fdata-sections -ffunction-sections -Wl,--gc-sections -L/rmkit/src/vendor/FBInk/Release -l:libfbink.a -DRMKIT_FBINK=1 -Wno-psabi -O2 -static -static-libstdc++ -static-libgcc
arm-kobo-linux-gnueabihf-g++ -c /rmkit/src/.harmony_cpp/main.cpp -o /rmkit/src/.harmony_cpp/main.o -DKOBO=1 -DRMKIT_IMPLEMENTATION -ldl -pthread -lpthread -fdata-sections -ffunction-sections -Wl,--gc-sections -L/rmkit/src/vendor/FBInk/Release -l:libfbink.a -DRMKIT_FBINK=1 -Wno-psabi -O2 -static -static-libstdc++ -static-libgcc
In file included from /rmkit/src/.harmony_cpp/main.cpp:3:
/rmkit/src/.harmony_cpp/../build/rmkit.h: In lambda function:
/rmkit/src/.harmony_cpp/../build/rmkit.h:22492:22: error: 'proc' has not been declared
22492 |         auto procs = proc::list_procs(bins);
      |                      ^~~~
missing file: stb_image.h
missing file: stb_image_resize.h
Couldn't compile /rmkit/src/.harmony_cpp/main.cpp aborting
compiled into /rmkit/src/.harmony_cpp
make[2]: *** [../actions.make:42: compile_kobo] Error 1
make[2]: Leaving directory '/rmkit/src/harmony'
make[1]: Leaving directory '/rmkit/src/harmony'
make[1]: *** [../actions.make:11: compile] Error 2
make: *** [Makefile:18: harmony] Error 2
```